### PR TITLE
Date toggle

### PR DESCRIPTION
**Pull request by bt-**
I added a date toggle to the plotDataFrame function and an example to the example iPython notebook.  I edited the generateJS function also to implement the date toggle feature.

### CODE REVIEW

**Comment by dinkelk** [comment]
Nice addition!! My ipython notebook version doesn't seem to play nicely with your changes. What version of ipython / ipython notebook are you using? I'd like to test out this change!

**Comment by bt-** [comment]
Notebook v3.0
Python 2.7.10 |Anaconda 2.2.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)]

I tested the example again after pushing it and realized it didn't work.  There were a couple import type bugs that I'll try to commit.

**Comment by dinkelk** [comment]
Thank you for contributing.

**Comment by bt-** [comment]
Happy to help, pydygraphs is a great combination of tools!

**Pull request merged**
