### PR TITLE
Cleaner String Formatting and Changing packaging layout

### PR DESCRIPTION
**Pull request by janga1997**
#4

### CODE REVIEW

**Comment by dinkelk** [comment]
Did you test this with `examples/PyDyGraphTester.ipynb`? It is not working for me:

```
PyDyGraphs/pydygraphs.py in generateJS(self)
    106           var data = JSON.parse(eval(json));
    107           var tabular = convertToDataTable_{0}(data);
--> 108           """.format(self._divname, self._x_axis)
    109 
    110         dygraphs += """

ValueError: unexpected '{' in field name
```
I am not sure that the python `{` and `}` string formatting is going to work when the string that we are trying to create is javascript, which includes `{` and `}` in its syntax. Thoughts?

**Comment by janga1997** [comment]
I did test it, but apparently it cached the unedited version.

That kinda throws water over using `.format()`. (Apparently, the only way to escape literal curly brackets in our string is to double them. And that will just be as ugly as before.)

We could use the older formatting style of Python
```
In [174]: "Hello %s %s"%('World', 34.45)
Out[174]: 'Hello World 34.45'
```

**Comment by dinkelk** [comment]
Yeah, let's try the older formatting style. We just need to be careful about the javascript modulo operator. But since that is used rarely, a few `%%` in the code won't look too ugly. We don't use a single modulo at the moment anyways.

**Comment by janga1997** [comment]
@dinkelk Offtopic, but have you taken a look at https://rstudio.github.io/dygraphs/ ?
We could use that as a base for future features to include.

**Comment by dinkelk** [comment]
@janga1997 That library looks excellent! I don't use R, so there is no surprise that I have never seen it. I like that idea. If pydygraphs ever became that feature-ful, I'd be very happy.

**Comment by dinkelk** [comment]
@janga1997 Similar question. Did you ever look at https://github.com/blacksburg98/dyplot before finding pydygraphs?

**Comment by janga1997** [comment]
@dinkelk Nope.
Just checked. Seems a rather roundabout way of generating plots. (Generating csv files and html files separately.)
And `dygraphs` seems to be only one component of it, that is, only line plots. The library also consists of scatter, bar, etc. plots using other js libs (c3.js, nvd3.js)

I'm a total noob, but if someone just needs interactive plots in Jupyter, they will probably use the `plotly` Python module. It covers all the plots anyone would ever need.

Where dygraphs.js shines is handling **large** datasets, because of rendering to canvas. I think we should stick to dygraphs only, and make the Python integration as good as possible.

**Comment by dinkelk** [comment]
@janga1997 Thank you for that insight. I agree with sticking to dygraphs and improving the Python integration.

**Comment by janga1997** [comment]
@dinkelk I hope you don't mind, but I also changed up the packaging structure, so moving forward, it is easier to work component by component.
The package name could be just `dygraphs` . (Similar to the R package, the 'py' is redundant)
the plotting functions are located in `graph.py`

Here is the structure.
```
dygraphs
├── series.py(future)
├── legend.py(future)
├── graph.py
├── __init__.py

```

Another thing I corrected for is how the module is imported.
Erstwhile, the module had to be imported as **`import pydygraphs`**,
otherwise, a line in the code 
`kernel.execute("pydygraphs.__PYDYGRAPH__FIGURE__JSON__ .... `
wouldn't work. (say for `import pydygraphs as pdy`)

So now, you can just do
**`import dygraphs.graph as dy`**, or whatever, and it works.

**Comment by dinkelk** [comment]
@janga1997 All of this looks great so far.

A few comments/questions. The original intent was to make the interface to the library feel a lot like pyplot. Looking back, I didn't do a perfect job of that. 

I am wondering two things:

1. Do you think emulating the pyplot API is a good approach?
2. Would we be better off trying to emulate the matplotlib API, the dygraphs R interface you have been referencing, MATLAB, or something else entirely?

If we stick with the current pyplot emulation, here would be what side-by-side might look like. Below is some pyplot code:

```
import matplotlib.pyplot as plt

plt.figure(1)
plt.plot(t, s)
plt.title('Figure 1')
plt.xlabel('x')
plt.ylabel('y')
plt.show()
```

And here would be the equivalent pydygraphs code:

```
import dygraphs.pyplot as plt

fig = plt.figure()
fig.plot(t, s)
fig.title("Figure 1")
fig.xlabel('x')
fig.ylabel('y')
fig.show()
```

Not identical, but pretty close. pydygraphs `figure()` function returns the figure object, similar to matplotlib, where as pyplot just assumes that the next call is using the current figure (similar to Matlab). Also, notice how I named the module `pyplot` to make the import statement even more similar to pyplot.

^^ So I am not advocating that this is necessarily the correct approach, but I am interested on your thoughts. I do, however, want to make sure we choose a direction and then stick with it as consistently as we can.

**Comment by janga1997** [comment]
@dinkelk I think its close enough to matplotlib the way it is right now, and that should be good enough, since most users will have used matplotlib at some point.

Edit :- Once we merge this, I am planning on adding labels, series, and axes customizations to this library.

**Pull request merged**
