### PR TITLE
Plot options

### PR DESCRIPTION
**Pull request by janga1997**

### CODE REVIEW

**Comment by janga1997** [comment]
I updated the Jupyter Notebook to reflect the latest changes.

Everything functions the same, but its now possible to add multiple data lines in a single argument.


```
size = 100
x = np.array(range(size))

y1 = np.sin(np.random.rand(size))
y2 = -np.sin(np.random.rand(size)) #Same shape, same number of rows
y3 = np.random.rand(size, 3) #Different shape, but same number of rows

fig.plot(x, y=(y1, y2, y3))
fig.show()

```
Note that it works regardless of the shape of the y values, but the number of rows must be the same.

**Comment by janga1997** [comment]
I also got rid of requirement to convert all data to a `DataTable`.
It just now prints as a native array into the JS array.

**Comment by dinkelk** [comment]
Gorgeous work. Great job simplifying the internals as well.

**Comment by dinkelk** [comment]
We should also update the README soon with new plot pictures. Since the new capabilities make for more beautiful plots.

**Pull request merged**
